---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  interval: 1m0s
  values:
    DNS1: 8.8.8.8
    DNS2: 8.8.4.4
    adlists: {}
    admin:
      existingSecret: pihole-secret
      passwordKey: password
    adminPassword: admin
    affinity: {}
    antiaff:
      avoidRelease: pihole1
      enabled: false
      strict: true
    blacklist: {}
    customVolumes:
      config: {}
      enabled: false
    dnsHostPort:
      enabled: false
      port: 53
    dnsmasq:
      additionalHostsEntries: []
      customCnameEntries: []
      customDnsEntries: []
      customSettings: null
      staticDhcpEntries: []
      upstreamServers: []
    doh:
      enabled: false
      envVars: {}
      name: cloudflared
      probes:
        liveness:
          enabled: true
          failureThreshold: 10
          initialDelaySeconds: 60
          timeoutSeconds: 5
      pullPolicy: IfNotPresent
      repository: crazymax/cloudflared
      tag: latest
    dualStack:
      enabled: false
    extraEnvVars: {}
    extraEnvVarsSecret: {}
    extraVolumeMounts: {}
    extraVolumes: {}
    ftl: {}
    hostNetwork: "false"
    hostname: ""
    image:
      pullPolicy: IfNotPresent
      repository: pihole/pihole
      tag: ""
    ingress:
      annotations: {}
      enabled: false
      hosts:
      - chart-example.local
      path: /
      tls: []
    maxSurge: 1
    maxUnavailable: 1
    monitoring:
      podMonitor:
        enabled: false
      sidecar:
        enabled: false
        image:
          pullPolicy: IfNotPresent
          repository: ekofr/pihole-exporter
          tag: 0.0.10
        port: 9617
        resources:
          limits:
            memory: 128Mi
    nodeSelector: {}
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      annotations: {}
      enabled: true
      existingClaim: pihole
      size: 5Gi
    podAnnotations: {}
    podDnsConfig:
      enabled: true
      nameservers:
      - 127.0.0.1
      - 8.8.8.8
      policy: None
    privileged: "false"
    probes:
      liveness:
        enabled: true
        failureThreshold: 10
        initialDelaySeconds: 60
        timeoutSeconds: 5
      readiness:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 60
        timeoutSeconds: 5
    regex: {}
    replicaCount: 1
    resources: {}
    serviceDhcp:
      annotations: {}
      enabled: false
      externalTrafficPolicy: Local
      loadBalancerIP: ""
      loadBalancerIPv6: ""
      type: NodePort
    serviceDns:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      externalTrafficPolicy: Local
      loadBalancerIP: 10.88.111.200
      loadBalancerIPv6: ""
      mixedService: false
      port: 53
      type: LoadBalancer
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      externalTrafficPolicy: Local
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      loadBalancerIP: 10.88.111.202
      loadBalancerIPv6: ""
      type: LoadBalancer
    strategyType: RollingUpdate
    tolerations: []
    topologySpreadConstraints: []
    virtualHost: pi.hole
    webHttp: "80"
    webHttps: "443"
    whitelist: {}
