---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  chart:
    spec:
      chart: kured
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubereboot
  interval: 10m0s
  targetNamespace: kube-system
