---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: home-assistant-repo
  interval: 1h0m0s
  values:
    addons:
      codeserver:
        enabled: enable
        service:
          type: LoadBalancer
    hostNetwork: true
    hostPort:
      enabled: false
      port: 8123
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 5Gi
      storageClass: nfs-client