config:
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services:
    - k8s hosted apps:
        - grafana:
            href: http://10.88.111.203:80
            description: Grafana Dashboard
            status: Online
        - prometheus:
            href: http://10.88.111.204:80
            description: Prometheus Monitoring
            status: Online
        - vscode:
            href: http://10.88.111.201:12321
            description: vscode online
            status: Online
        - pihole-web:
            href: http://10.88.111.200:80
            description: Pi-hole Web Interface
            status: Online
        - home-assistant:
            href: http://10.88.111.29:8123/
            description: home assistant 
            status: Online
    - Infra:
        - hv-one:
            href: http://10.88.111.252:8006
            description: proxmox via hv-one
            status: Online
        - hv-two:
            href: http://10.88.111.253:8006
            description: proxmox via hv-two
            status: Online
    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets:
    # show the kubernetes widget, with the cluster summary and individual nodes
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  kubernetes:
    mode: cluster
  settings:

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true